oidc:
  issuer: https://id.example.com/auth/realms/master
  clientID: kubernetes
  usernameClaim: preferred_username
  groupsClaim: groups
  usernamePrefix: "oidc:"
  groupsPrefix: "oidc:"
  requiredClaims: []
  # requiredClaims: ["test=yes"]

deployment:
  image:
    registry: docker.io
    repository: tremolosecurity
    name: kube-oidc-proxy
    tag: null
    pullPolicy: IfNotPresent
    pullSecrets: []
  replicas: 2
  strategy:
    type: RollingUpdate
  resources:
    requests:
      memory: "128Mi"
      cpu: "500m"
    limits:
      memory: "128Mi"
      cpu: "500m"

service:
  type: ClusterIP
  annotations: null
  externalTrafficPolicy: null

ingress:
  enabled: false
  annotations: null
  hosts:
    - api.kubernetes.example.com
  tlsSecret: null
  ingressClassName: null

tls:
  secretName:

affinity: {}

tolerations: []

podDisruptionBudget:
  enabled: false
  minAvailable:
  maxUnavailable:
